<?php

    echo nl2br("1)Write a PHP script to transform a string all uppercase letters.\n");
        $the_string = 'abcdefghijklmnopqrstuvwxyz';
        $the_string = strtoupper($the_string);
        echo nl2br($the_string . "\n");
        echo nl2br("\n");
    echo nl2br("1)Write a PHP script to transform a string all lowercase letters.\n");
        $the_string = strtolower($the_string);
        echo nl2br($the_string . "\n");
        echo nl2br("\n");
    echo nl2br("1)Write a PHP script to make a string's first character uppercase.\n");
        $the_string = ucfirst($the_string);
        echo nl2br($the_string . "\n");
        echo nl2br("\n");
    echo nl2br("1)Write a PHP script to make a string's first character of all the words uppercase.\n");
        $another_string = ucwords('more words for the example');
        echo nl2br($another_string . "\n");
        echo nl2br("\n");
    echo nl2br("2) Write a PHP script to split the following string.\n");
    echo nl2br("Sample string : 082307
          Expected Output : 08:23:07\n");
        $the_split = str_split("082307", 2);
        $the_reunited = implode(':', $the_split);
        echo nl2br($the_reunited . "\n");
        echo nl2br("\n");
    echo nl2br("3) Write a PHP script to check if a string contains specific string?\n");
        $the_search_one = "24";
        if(strpos($the_string, $the_search_one))
            echo nl2br("We find it\n");
        else
            echo nl2br("Take another shot\n");
        echo nl2br("\n");
    echo nl2br("4) Write a PHP script to convert the value of a PHP variable to string.\n");
        $a_value = 420.69;
        $the_conversion = strval($a_value);
        echo nl2br($the_conversion . "\n");
        echo nl2br("\n");
    echo nl2br("5) Write a PHP script to extract the file name from the following string.
             Sample String : 'www.example.com/ public_html index.php\n");
        $sample1 = 'www.example.com/ public_html index.php';
        echo nl2br(substr(strchr($sample1, '/'), 1) . "\n");
        echo nl2br("\n");
    echo nl2br("6) Write a PHP script to extract the user name from the following email ID.\n");
        $my_email = 'mihaitudor2000@yahoo.com';
        echo nl2br(strstr($my_email, '@', true) . "\n");
        echo nl2br("\n");
    echo nl2br("7) Write a PHP script to get the last three characters of a string.\n");
        echo nl2br(substr ($the_string, - 3) . "\n");
        echo nl2br("\n");
    echo nl2br("8)Write a PHP script to format values in currency style:\n");
        $the_value1 = 65.45;
        $the_value2 = 104.35;
        $the_sum = number_format($the_value1 + $the_value2, 2);
        echo nl2br($the_sum . "\n");
        echo nl2br("\n");
    echo nl2br("9)Write a PHP script to generate simple random password from a given string:\n");
        $the_password = "1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcefghijklmnopqrstuvwxyz";
        $the_password = str_split($the_password);
        shuffle($the_password);
        $the_password = implode($the_password);
        echo nl2br(substr($the_password, 0, 8) . "\n");
        echo nl2br("\n");
    echo nl2br("10)Write a PHP script to replace the first 'the' of the following string with 'That':\n");
        $the_string = "the quick brown fox jumps over the lazy dog.";
        $the_string = substr_replace($the_string,"That",0,3);
        echo nl2br($the_string . "\n");
        echo nl2br("\n");
    echo nl2br("11)Write a PHP script to find first character that is different between two strings:\n");
        $the_s1 = "football";
        $the_s2 = "footboll";
        $the_position = strspn($the_s1 ^ $the_s2, "\0");
        echo nl2br("The first character that is different between those two is: " . $the_s1[$the_position] . " !== "
        . $the_s2[$the_position] . "\n");
        echo nl2br("\n");
    echo nl2br("12)Write a PHP script to get the filename component of the following path:\n");
        $the_source = "https://www.w3resource.com/index.php";
        $the_rez = strstr(substr(strrchr($the_source,"/"),1), ".", true);
        echo nl2br($the_rez . "\n");
        echo nl2br("\n");
    echo nl2br("13)Write a PHP script to print the next character of a specific character:\n");
        $the_cha = 'z';
        $the_next_cha = ++$the_cha;
        if (strlen($the_next_cha) > 1)
            $the_next_cha = $the_next_cha[0];
        echo nl2br($the_next_cha . "\n");
        echo nl2br("\n");
    echo nl2br("14)Write a PHP script to remove a part of a string from the beginning:\n");
        $the_sample = "rayy@example.com";
        $the_sample = substr($the_sample, 5);
        echo nl2br($the_sample . "\n");
        echo nl2br("\n");
    echo nl2br("15)Write a PHP script to get a hex dump of a string:\n");
        $the_sample = "rayy@example.com";
        $the_hex =  bin2hex($the_sample);
        echo nl2br($the_sample . "\n");
        echo nl2br("\n");
    echo nl2br("16)Write a PHP script to insert a string at the specified position in a given string:\n");
        $the_destination = "The brown fox";
        $after_insertion = substr_replace($the_destination," quick ",4,0);;
        echo nl2br($after_insertion . "\n");
        echo nl2br("\n");
    echo nl2br("17)Write a PHP script to get the first word of a sentence:\n");
        $just_a_string = "The quick brown fox";
        $just_a_word = strstr($just_a_string, " ", true);
        echo nl2br($just_a_word . "\n");
        echo nl2br("\n");
    echo nl2br("18)Write a PHP script to remove all leading zeroes from a string:\n");
        $the_problematic = "000547023.24";
        $the_normal_one = ltrim($the_problematic, "0");
        echo nl2br($the_normal_one . "\n");
        echo nl2br("\n");
    echo nl2br("19)Write a PHP script to remove part of a string:\n");
        $the_original = "The quick brown fox jumps over fox the lazy dog";
        $the_remix = substr_replace($the_original,"", 16, 3);
        echo nl2br($the_remix . "\n");
        echo nl2br("\n");
    echo nl2br("20)Write a PHP script to remove trailing slash from a string:\n");
        $not_the_cute_one = "The quick brown fox jumps over the lazy dog///";
        $the_cute_one = rtrim($not_the_cute_one,"/");
        echo nl2br($the_cute_one . "\n");
        echo nl2br("\n");
    echo nl2br("21)Write a PHP script to get the characters after the last '/' in an url:\n");
        $the_support = "https://www.php.net/manual/en/function.strrchr";
        $the_result = substr(strrchr($the_support, '/'), 1);
        echo nl2br($the_result . "\n");
        echo nl2br("\n");
    echo nl2br("22)Write a PHP script to replace multiple characters from the following string:\n");
        $the_string = "njjjojjjjw I'jjjjm kkkkk comhhphhhhlekkkkt\n";
        $the_spoiled_one = str_replace(['h', 'j', 'k'], '', $the_string);
        echo nl2br($the_spoiled_one);
        echo nl2br("\n");
    echo nl2br("23)Write a PHP script to select first 5 words from the following string:\n");
        $the_string = "The quick brown fox jumps over fox the lazy dog";
        $the_string = implode(' ', array_slice(explode(' ', $the_string), 0, 5));
        echo nl2br($the_string . "\n");
        echo nl2br("\n");
    echo nl2br("24)Write a PHP script to remove comma(s) from the following numeric string\n");
        $the_string_with_commas = "h,,ehe,h,eheh,,eheh,,eh,eh,,,";
        $the_string_without = str_replace(",", "", $the_string_with_commas);
        echo nl2br($the_string_without . "\n");
        echo nl2br("\n");
    echo nl2br("25)Write a PHP script to print letters from 'a' to 'z':\n");
        $letters = range('a', 'z');
        foreach ($letters as $value) {
            echo $value;
        }
        echo nl2br("\n");
        echo nl2br("\n");
    echo nl2br("26)What will display the next code:\n");
        $d = 'Aoo';
        echo nl2br(++$d . "\n");
        echo nl2br('Will increment the value in bits of the string by 1, before printing' . "\n");